FROM node:20-alpine
WORKDIR /app
COPY frontend/package.json frontend/tsconfig.json frontend/next-env.d.ts frontend/next.config.ts /app/
COPY frontend/src /app/src
RUN npm install
CMD ["npm", "run", "dev"]
